import { useState } from 'react';
import Head from 'next/head';
import type { NextPage } from 'next';
import axios from 'axios';
import { useUser } from '@auth0/nextjs-auth0';
import { RiDeleteBin2Fill } from 'react-icons/ri';

const Directors: NextPage<{ directors: any }> = ({
	directors,
}: {
	directors: any;
}) => {
	const [show, setShow] = useState(false);
	const { user } = useUser();

	const handleDelete = async (id: number) => {
		await axios.delete(`http://127.0.0.1/director/${id}`);
	};

	return (
		<div>
			<Head>
				<title>Directors - Watchlist</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1 className='text-2xl font-bold'>Directors</h1>
				<div className='flex flex-col items-center sm:grid sm:grid-cols-4 sm:gap-x-4'>
					{directors.map((director: any) => (
						<div key={director.id} className='py-8 space-y-2'>
							<img
								className='rounded-md shadow shadow-gray-200'
								width={214}
								height={317}
								src={director.avatar}
								alt={director.fullname}
							/>
							<div className='flex items-center space-x-2 md:space-x-4'>
								<div>
									<h2 className='font-bold text-lg w-44 truncate'>
										{director.fullname}
									</h2>
									<p className='text-gray-500'>{director.nationality}</p>
								</div>
								{user ? (
									<button
										onClick={() => handleDelete(director?.id)}
										className='text-red-600 hover:text-red-800 transition duration-300'>
										<RiDeleteBin2Fill className='h-5 w-5' />
									</button>
								) : null}
							</div>
						</div>
					))}
				</div>
			</main>
		</div>
	);
};

export async function getServerSideProps() {
	const response = await axios.get('http://127.0.0.1:3000/directors');

	return {
		props: {
			directors: response.data,
		},
	};
}

export default Directors;
