import { useQuery } from '@tanstack/react-query';
import type { NextPage } from 'next';
import Head from 'next/head';
import {
	RiFilmFill,
	RiFlagFill,
	RiLoader4Fill,
	RiUserFill,
} from 'react-icons/ri';

import { fetchStatistics } from 'lib/statistics';
import { MPCChart } from 'components/Charts/MPCChart';
import { STWChart } from 'components/Charts/STWChart';
import { StatisticsPage } from 'types/Chart';
import { StatCard } from 'components/Misc/StatCard';

const Home: NextPage<{ statistics: StatisticsPage }> = ({ statistics }) => {
	const { isLoading, isError, error, data } = useQuery(
		['statistics'],
		fetchStatistics,
		{
			initialData: statistics,
		}
	);
	const highestMovieNumber = Math.max(
		...statistics.mpc.map((data) => data.value)
	);

	if (isLoading) {
		return (
			<div className='fixed inset-0 h-screen'>
				<RiLoader4Fill className='h-6 w-6 animate-spin-slow' />
			</div>
		);
	}

	return (
		<div>
			<Head>
				<title>Watchlist</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<section className=''>
				<h1 className='text-2xl font-bold'>Statistics</h1>
				<div className='mt-4 grid grid-cols-1 gap-4 sm:grid-cols-3'>
					<StatCard
						title='Movies'
						stat={data.movies}
						icon={<RiFilmFill className='h-4 w-4' />}
					/>
					<StatCard
						title='Directors'
						stat={data.directors}
						icon={<RiUserFill className='h-4 w-4' />}
					/>

					<StatCard
						title='Movies'
						stat={data.movies}
						icon={<RiFlagFill className='h-4 w-4' />}
					/>
				</div>
			</section>
			<section className='mt-12 grid grid-cols-1 lg:grid-cols-2'>
				<div>
					<MPCChart data={data.mpc} hmn={highestMovieNumber} />
				</div>
				<div>
					<STWChart data={data.stw} />
				</div>
			</section>
		</div>
	);
};

export async function getServerSideProps() {
	const response = await fetchStatistics();

	return {
		props: {
			statistics: response,
		},
	};
}

export default Home;
