import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query';
import type { NextPage } from 'next';
import Head from 'next/head';
import { RiFilmFill, RiFlagFill, RiUserFill } from 'react-icons/ri';

import { fetchStatistics } from 'lib/statistics';
import { MPCChart } from 'components/Charts/MPCChart';
import { STWChart } from 'components/Charts/STWChart';
import { StatCard } from 'components/Misc/StatCard';

const Home: NextPage = () => {
	const { isLoading, data } = useQuery(['statistics'], fetchStatistics);

	if (isLoading) {
		return (
			<div className='fixed inset-0 h-screen flex flex-col justify-center items-center'>
				<h1 className='text-4xl font-bold'>Loading Data ...</h1>
			</div>
		);
	}

	return (
		<div>
			<Head>
				<title>Watchlist</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<section className=''>
				<h1 className='text-2xl font-bold'>Statistics</h1>
				<div className='mt-4 grid grid-cols-1 gap-y-8 lg:gap-y-0 gap-x-4 sm:grid-cols-3'>
					<StatCard
						title='Movies'
						stat={data.movies}
						icon={<RiFilmFill className='h-4 w-4' />}
					/>
					<StatCard
						title='Directors'
						stat={data.directors}
						icon={<RiUserFill className='h-4 w-4' />}
					/>

					<StatCard
						title='Countries'
						stat={data.countries}
						icon={<RiFlagFill className='h-4 w-4' />}
					/>
				</div>
			</section>
			<section className='mt-12 grid grid-cols-1 lg:grid-cols-2'>
				<div>
					<MPCChart data={data.mpc} />
				</div>
				<div>
					<STWChart data={data.stw} />
				</div>
			</section>
		</div>
	);
};

export async function getStaticProps() {
	const queryClient = new QueryClient();
	await queryClient.prefetchQuery(['movies'], fetchStatistics);

	return {
		props: { dehydratedState: dehydrate(queryClient) },
	};
}

export default Home;
