import { useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';
import type { NextPage } from 'next';
import axios from 'axios';
import { useUser } from '@auth0/nextjs-auth0';
import { RiDeleteBin2Fill } from 'react-icons/ri';

import { Notification } from 'components/Misc/Notification';
import { Movie, Movies } from 'types/Movie';

const Movies: NextPage<{ movies: Movies }> = ({ movies }) => {
	const [show, setShow] = useState(false);
	const { user } = useUser();

	const handleDelete = async (id: number) => {
		await axios.delete(`http://localhost:3000/movie/${id}`);
		setShow(true);
	};

	return (
		<div>
			<Head>
				<title>Movies - Watchlist</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1 className='text-2xl font-bold'>Movies</h1>
				<div className='py-8 flex flex-col items-center sm:grid md:grid-cols-3 lg:grid-cols-4 gap-y-6 sm:gap-x-4'>
					{movies.map((movie: Movie) => (
						<Link key={movie?.id} href={`/movies/${movie.id}`}>
							<a className='group '>
								<div className='space-y-4'>
									<img
										className='group-hover:hover:scale-105 shadow-md shadow-gray-200 rounded-md transition duration-300 '
										width={217}
										height={314}
										src={movie?.cover || '/covers.png'}
										alt={`${movie?.title} Cover`}
									/>
									<div className='flex items-center space-x-2 lg:space-x-4'>
										<div>
											<h2
												className='text-lg font-bold w-44 truncate'
												aria-label={movie?.title}>
												{movie?.title}
											</h2>
										</div>
										{user ? (
											<button
												onClick={() => handleDelete(movie?.id)}
												className='text-red-600 hover:text-red-800 transition duration-300'>
												<RiDeleteBin2Fill className='h-5 w-5' />
											</button>
										) : null}
									</div>
								</div>
							</a>
						</Link>
					))}
				</div>
			</main>
			<Notification
				show={show}
				setShow={setShow}
				title='Successfully Deleted'
				text='a record has been deleted from the database'
			/>
		</div>
	);
};

export async function getServerSideProps() {
	const response = await axios.get('http://127.0.0.1:8080/movies');

	return {
		props: {
			movies: response.data,
		},
	};
}

export default Movies;
